author: MDCollins
database: false
description: Rewards people who plant saplings, but has limitations to avoid abuse.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.saplingrewards.SaplingRewards
name: SaplingRewards
startup: postworld
url: http://blockmovers.com/
version: '0.5'
depend: [Vault]
commands:
  saplingrewards:
    usage: /<command>
    aliases: sr
permissions:
  sr.admin:
    default: false
    description: Allows the player access to the admin commands
  sr.break.allow:
    default: false
    description: Allows the player to break saplings
  sr.break.disallow:
    default: false
    description: Disallows the player to break saplings
  sr.close.plant.allow:
    default: false
    description: Allows planting saplings too close
  sr.close.plant.disallow:
    default: false
    description: Disallows planting saplings too close
  sr.close.reward.allow:
    default: false
    description: Rewards players when planting too close
  sr.close.reward.disallow:
    default: false
    description: Does not reward players when planting too close