author: MDCollins
database: false
description: Rewards people who plant saplings, but has limitations to avoid abuse.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.saplingrewards.SaplingRewards
name: SaplingRewards
startup: postworld
url: http://blockmovers.com/
version: '0.3'
depend: [Vault]
commands:
  saplingrewards:
    usage: /<command>
    aliases: sr
permissions:
  sr.nobreak:
    default: false
    description: Does not allow players to break saplings
  sr.nobreak.override:
    default: false
    description: This is the override for allowing the breaking of saplings
